apiVersion: v1
kind: ConfigMap
metadata:
  name: devlake-helm-chart-value-overrides
  namespace: devlake
data:
  values.yaml: |-
    replicaCount: 1
    commonEnvs:
      TZ: "UTC"
    grafana:
      enabled: false
      external:
        url: "https://grafana.pd.nttdataco.com"
    lake:
      encryptionSecret:
        secret: "LXVDKQYKJZBRPPGGVXRPIBDZZDPYHSAWNYXUOHPYPNWVWFDGAQONGTCWZNNZXPJSAZZXCZRQSFUSMPLOORWPEDCIUZCKJYRHNGJNJYLOGHJUYKOXSAWHDIANQUGLSCCT"

    ingress:
      enabled: true
      enableHttps: true
      useDefaultNginx: true
      className: "nginx"
      hostname: "devlake.pd.nttdataco.com"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tlsSecretName: "devlake-tls"