#https://github.com/bitnami/charts/tree/main/bitnami/redis
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: "7.3.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: grafana-helm-chart-value-overrides
      valuesKey: values.yaml
