apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-helm-chart-value-overrides
  namespace: ingress-nginx
data:
  values.yaml: |-
    controller:
      service:
        externalTrafficPolicy: Local
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
      opentelemetry:
        enabled: true
      config: 
        enable-opentelemetry: "true"
        otlp-collector-host: "main-collector-collector.main-collector.svc.cluster.local"
        otlp-collector-port: "4317"
        otel-max-queuesize: "2048"
        otel-schedule-delay-millis: "5000"
        otel-max-export-batch-size: "512"
        otel-service-name: "ingress-nginx"
        otel-sampler: "AlwaysOn"
        otel-sampler-ratio: "1.0"
        otel-sampler-parent-based: "false"
        opentelemetry-config: "/etc/nginx/opentelemetry.toml"
        opentelemetry-operation-name: "HTTP $request_method $service_name $uri"
        opentelemetry-trust-incoming-span: "true"