apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-helm-chart-value-overrides
  namespace: ingress-nginx
data:
  values.yaml: |-
    controller:
      service:
        externalTrafficPolicy: Local
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
          service.beta.kubernetes.io/load-balancer-internal: "true"
          service.kubernetes.io/cluster-service-endpoint: "true"
          service.kubernetes.io/service-proxy-name: "nginx-ingress-controller"
          service.spec.loadBalancerClass: "internal"
# Asignar la subred específica al balanceador de carga interno
          subnets:
            - "192.168.100.0/24"
# que quede como balanceador de carga interno en la s net que aprobiciona mauro y jessica
# balanceador de carga en la subnet que se va asignar 

      config: 
        
        otlp-collector-host: "main-collector-collector.main-collector.svc.cluster.local"
        otlp-collector-port: "4317"
        otel-max-queuesize: "2048"
        otel-schedule-delay-millis: "5000"
        otel-max-export-batch-size: "512"
        otel-service-name: "ingress-nginx"
        otel-sampler: "AlwaysOn"
        otel-sampler-ratio: "1.0"
        otel-sampler-parent-based: "false"