#https://github.com/bitnami/charts/tree/main/bitnami/cassandra
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 5m
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: "4.9.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx-helm-chart-value-overrides
      valuesKey: values.yaml